function nicePlot(FIGURE, AXES)

    set(FIGURE, ...
          'Units'       , 'pixels', ...
          'Position'    , [100 100 1000 350], ...
          'MenuBar'     , 'none', ...
          'ToolBar'     , 'none', ...
          'Color'       , [1 1 1]);
    set(AXES, ...
          'Box'         , 'off'     , ...
          'TickDir'     , 'out'     , ...
          'TickLength'  , [.02 .02] , ...
          'XMinorTick'  , 'on'      , ...
          'YMinorTick'  , 'on'      , ...
          'XGrid'       , 'on'      , ...
          'YGrid'       , 'on'      , ...
          'XColor'      , [.3 .3 .3], ...
          'YColor'      , [.3 .3 .3], ...
          'LineWidth'   , 1         );

end